name: CMake MSVC

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        preset:
          - vs2022-x64-debug
          - vs2022-x64-release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Toolchain info
        shell: pwsh
        run: |
          cmake --version
          ctest --version

      - name: Configure
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }} --parallel

      - name: Test
        run: ctest --preset ${{ matrix.preset }}
